
name: RunBenchmark
on:
  push:

jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: instantiate environment
        run: |
            pwd
            ls
            ls OrbitalElements.jl

      - name: benchmark
        run: julia tests/benchmarks.jl
