
name: RunBenchmark
on:
  push:

jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: instantiate environment
        run: |
            julia -e '
              using Pkg
              Pkg.add(url="https://github.com/michael-petersen/OrbitalElements.jl.git")
              Pkg.develop(PackageSpec(path="/home/runner/work/OrbitalElements.jl/")'
      - name: benchmark
        run: julia tests/benchmarks.jl
