name: CI lite
on:
  pull_request:
    branches:
      - v2.0
    paths:
      - src/**
      - test/**
  push:
    branches:
      - v2.0
    paths:
      - src/**
      - test/**
jobs:
  devtest:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.10' # Leave this line unchanged. '1' will automatically expand to the latest stable 1.x release of Julia.
          arch: x64
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info